export const ADD_FLASHCARD = "ADD_FLASHCARD";
export const REMOVE_FLASHCARD = "REMOVE_FLASHCARD";
export const GROUP_ID_TO_DOWNLOAD = "GROUP_ID_TO_DOWNLOAD";
export const CARD_ID_TO_DOWNLOAD = "CARD_ID_TO_DOWNLOAD";
export const CARD_ID_TO_PRINT = "CARD_ID_TO_PRINT";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
